- vcl_templates/assets.vcl.erb
- vcl_templates/bouncer.vcl.erb
- vcl_templates/performanceplatform.vcl.erb
- vcl_templates/performanceplatform_admin.vcl.erb
- vcl_templates/performanceplatform_stagecraft.vcl.erb
- vcl_templates/www.vcl.erb
These were introduced in 255a629 and 03cb1fc5 to help demarcate our
customisations from Fastly's default VCL configuration. I think they may
also appear in Fastly's default VCL configuration.
While I agree with the original reasons for adding these, in practice
these markers have moved around and I think they're no longer
accurate, i.e. they're misleading. I also think they hamper readability
to a small extent.
> Remove custom markers from VCL

- vcl_templates/apt.vcl.erb
- vcl_templates/assets.vcl.erb
- vcl_templates/performanceplatform.vcl.erb
- vcl_templates/performanceplatform_admin.vcl.erb
- vcl_templates/performanceplatform_stagecraft.vcl.erb
- vcl_templates/www.vcl.erb
Our timeouts when connecting to the origin are different in our `www`,
`assets` and `performanceplatform*` services.
Make them consistent, using these values:
first_byte_timeout = 15s
between_bytes_timeout = 10s
These seem more appropriate than the previous values of 120s, used for
for both timeouts, in the `www` service:
- 15 seconds is long enough to make a user wait (referring to the first
byte timeout); in that case it's probably best to failover to the
mirror
- Nginx, which we use at origin, already buffers proxied requests from
upstreams, so it's unlikely that more than 10 seconds would pass
between bytes for reasons other than networking:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering
Also set the probe interval to 10 seconds, which seems more …
> Make our VCL configuration more consistent

- vcl_templates/performanceplatform.vcl.erb
backdrop-write now offers a PATCH route, allowing attributes in Mongo documents (data set collections) to be updated. This PR configures Fastly to allow PATCH requests to be routed through.
> Allow PATCH requests to backdrop-write

- vcl_templates/servicegovuk.vcl.erb
Add configuration template for service.gov.uk to replace the current AWS
implementation with Fastly:
- Redirect HTTP for service.gov.uk to HTTPS service.gov.uk
- Redirect HTTPS service.gov.uk to www.gov.uk
- Set HSTS header on HTTPS reponse
> Add configuration for service.gov.uk

- vcl_templates/www.vcl.erb
Add Varnish config specifically for the 'frontend' app, and configure it to set cookies and headers for an A/B test.
The A/B testing approach follows https://www.fastly.com/blog/ab-testing-edge, and uses a mixture of cookies and custom headers:
- Users are placed into A/B buckets in the Varnish config, rather than in the app. This means that a user can visit the site for the first time and be assigned an A/B testing cookie without their request necessarily hitting the app server, because the response comes from the cache and the cookie was added by Varnish
- The cookie is transformed into a custom header in Varnish, and we vary by that header. This means that the CDN and the govuk Varnish just cache two versions of the page - one for each A/B test variant. This avoids varying by cookie, …
> Configure A/B testing cookies and headers

- vcl_templates/www.vcl.erb
Two commits to address @alexmuller's comments on #13, which I merged too early:
- Make cookie check consistent in `vcl_recv` and `vcl_deliver`
- Rename header because the 'X-' prefix is deprecated, following [RFC 6648|https://tools.ietf.org/html/rfc6648]
https://trello.com/c/QyDbSiR9/289-allow-a-b-testing-cookies-to-be-set
I'll rename the header in alphagov/frontend#1099 as well.
> Fix A/B test issues in Varnish config

- vcl_templates/www.vcl.erb
In order to improve UX responses from the mirror should either return a 200 status code (found) or a 503 (service not available). This is because there are many URLs that the mirrors do not cache that are valid (for example, `/search`). In these cases whilst it is technically correct to return a 404 this is likely to confuse a user who would assume they have mis-typed the URL rather than, as is the case, hit the website during an outage. The user response we would like to encourage in this case is retrying in a little while once the site has returned.
To return 503s for non-200 responses we have changed the varnish configuration for fastly so that any response from a mirror which isn't a 200 has its status code set to 503.
> Treat any non-200 from a mirror as a 503

- vcl_templates/www.vcl.erb
The A/B example cookie is only used for testing purposes. It's not relevant to most users, and setting it on every response is excessive.
Trello: https://trello.com/c/g4C5JaTU/355-only-set-the-abtest-example-cookie-if-the-user-visits-the-example-a-b-test-page-to-prevent-us-from-setting-the-cookie-for-every-
> Only set the A/B example cookie if users visit the A/B test page

- vcl_templates/www.vcl.erb
This change flips the A/B fraction calculation so it calculates the fraction of users in the B group, to be consistent with how we talk about A/B tests.
We usually talk about A/B tests in terms of the fraction of users who see the B version, which is the newer version. So "0%" would mean the experiment hasn't started yet, and "100%" would mean that everyone is being shown the new version.
> Invert the A/B split logic to improve readability

- vcl_templates/www.vcl.erb
Identify requests from the mirror's crawler worker, and set the request header such that it only ever sees the original 'A' version of the example A/B test.
This is in preparation for the real A/B test of education navigation. It will affect many pages across the site, so it's important to make sure that the mirror contains a self-consistent version of all the affected pages.
Trello: https://trello.com/c/0v9u9TOs/353-ensure-that-the-gov-uk-mirror-only-mirrors-the-a-version-of-all-tests
The user-agent string comes from govuk_crawler_worker: https://github.com/alphagov/govuk_crawler_worker/blob/master/http_crawler/crawler.go#L71
> Ensure the GOV.UK mirror stores the original version of the A/B test

- vcl_templates/tldredirect.vcl.erb
This is the first 2 steps in https://github.com/alphagov/govuk-cdn-config/issues/14
It copies the code from `servicegovuk.vcl.erb` to redirect http://gov.uk/whatever to https://gov.uk/whatever and it sets a 10 second max-age to limit the damage if anything goes wrong.
I don't have a fastly account to test this against, so it's a little speculative.
> Make the raw domain HTTPS upgrade HSTS compatible and set 10 sec max-age

- vcl_templates/www.vcl.erb
Add missing bracket to fix the deployment of the www config. 😞 
The deployment step failed because the syntax error, but Jenkins reported the fastly-configure job as a success. Could we also make the job fail when this happens? (There's always the [text-finder plugin](https://wiki.jenkins-ci.org/display/JENKINS/Text-finder+Plugin) if we can't identify the failure any other way.)
Trello: https://trello.com/c/0v9u9TOs/353-ensure-that-the-gov-uk-mirror-only-mirrors-the-a-version-of-all-tests
> Fix syntax error in www config

- vcl_templates/tldredirect.vcl.erb
The 10 second max-age introduced in #20 seems to be fine. This
commit increases that to 1 hour (3600 seconds), as a further step
outlined in #14.
> Bump TLD redirect HSTS max-age to 1 hour

- vcl_templates/www.vcl.erb
For: https://trello.com/c/JX541tka/113-add-tls-version-information-to-google-analytics
Also see https://github.com/alphagov/static/pull/900 which consumes this cookie.  Our goal here is to set a cookie with the tls protocol version as understood by fastly and then read the cookie in the frontend so we can send the protocol version to GA and let us work out how many visitors use each version of the protocol.  This will ultimately inform our decisions about when/if to drop support older versions of the protocol (see: [Fastly's plan to deprecate 1.0 and 1.1](https://www.fastly.com/blog/phase-two-our-tls-10-and-11-deprecation-plan).
> Add tls cookie

- vcl_templates/www.vcl.erb
- Configure a cookie and custom header for the Education Navigation A/B test.
- For now, set the 'B' fraction to 0. This lets developers and remote testers access the 'B' variant without releasing it to the general public yet.
- For now, configure a short cookie expiry time (1 day) so that we don't end up with users stuck seeing the 'A' version when the A/B test starts.
- Use query string to switch between navigation A/B test variants. This allows us to send a link containing this query string to remote testers to ensure that they only see the B variant of the site.
> Configure an A/B test for the new education navigation

- vcl_templates/www.vcl.erb
Remote testers will be sent a URL like https://www.gov.uk?ABTest-EducationNavigation=B to ensure that they see a specific version of the A/B test. This was broken if they already had
an A/B testing cookie, because Fastly would not overwrite the existing cookie.
This commit makes ensures the correct cookie is set if the URL contains the A/B test query string, regardless of whether the user had an existing cookie.
Trello: https://trello.com/c/F2L41y9R/321-pre-release-of-beta-roll-out-the-new-navigation-via-a-b-testing-to-remote-testers-before-the-general-public
> Fix ABTest-EducationNavigation cookie setting for remote testers

- vcl_templates/www.vcl.erb
The `vcl_deliver` block still fires during an HTTP → HTTPS upgrade, so we [write the TLS version cookie with a `(null)` value](https://gist.github.com/davidillsley/8dc427420704d21e8f5a3f3d27bdbb26), and don't update it when a valid value actually exists.  This change avoids writing the cookie in the first place if we have a null value.
Note: this doesn't take in to account anyone who already has a null value set in a cookie, but as they're session cookies and will be expired on browser close, this is acceptable.
> Avoid writing null TLS cookies on http>https upgrade

- vcl_templates/www.vcl.erb
Increase the B fraction from 0/10 to 1/10 to start the Education Navigation A/B test.
Also increase the A/B test cookie expiry from 1 day to 1 year, so that users see the same variant throughout the test.
Marked as DO NOT MERGE because we want to control when we deploy this.
Trello: https://trello.com/c/pCvpvtds/356-roll-out-the-navigation-a-b-test-to-the-general-public
> Show the B version of the Education Navigation A/B test to 10% of users

- vcl_templates/www.vcl.erb
Varnish doesn't know that `y` means years, so we'll have to count in days instead.
```
Unknown time unit 'y'.  Legal are 'ms', 's', 'm', 'h' and 'd' (input Line 430 Pos 124)
add resp.http.Set-Cookie = "ABTest-EducationNavigation=" req.http.GOVUK-ABTest-EducationNavigation "; expires=" now + 1y "; path=/";
```
> Use days rather than years in VCL

- vcl_templates/www.vcl.erb
Previously we were checking the `tls.client.protocol` value against a literal string of `(null)`, which is what the cookie value ended up as if the request was via HTTP.  But the actual value is not the same as the string representation, so the check was always passing (i.e. it never matched `(null)`)."
> Fix null TLS protocol detection

- vcl_templates/www.vcl.erb
We are enabling the new navigation pages for everyone that goes directly
to them. The reason for this is to avoid people seeing 404s, and search
indexers index pages that might point people to 404s.
This is a complementary change where we assign users to the B group when
they go directly to a new navigation page, so they see a consistent
navigation throughout the site.
All new navigation pages start with `/education`.
cc/ @suzannehamilton @tijmenb
> Add users to B group when going to a nav page

- vcl_templates/www.vcl.erb
When adding smokey tests to verify we were assigning users to the
expected bucket, we realised we used a cache busting param to the
request. In doing so, the request wasn't recognised as being a request
to /education, meaning we weren't being assigned to the correct bucket.
This change makes sure we also allow for `?` after /education.
> Allow query params on /education URLs

- vcl_templates/www.vcl.erb
This commit makes sure 30% of new sessions will see the new Education
Navigation in GOV.UK.
This was a product decision so we can ramp up our numbers.
> Increase sessions in B variant to 30%

- vcl_templates/www.vcl.erb
Opening #22 again. This is a re-run of the experiment described in https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/
The original experiment didn't use cookies, but we're using cookies as an enhancement to track unique users and possibly filter out any pre-scanning behaviour by browsers which could possibly skew the number of users appearing to use javascript.
https://www.gov.uk/help/cookies now has a description of this cookie.
> Js detection cookie

- vcl_templates/www.vcl.erb
We are going to be running a new A/B test for the GOV.UK benchmarking
task. In this A/B test, which should last less than 1 week, we will be
adding a tracking library so we understand how users interact with the
new navigation pages we have exposed for Education content.
In this commit we add rules to set the ABTest-Benchmarking cookie based
on a few things.
On `vcl_recv`:
- If the user visits GOV.UK with a parameter like
`?ABTest-Benchmarking=B`, we will use that value to set the header
accordingly, so the application knows what variant to render (and set
the `Vary` header appropriately);
- If the user already has a cookie set, we use that value in the
header, so the application knows what variant to render (and set
the `Vary` header appropriately);
- Finally, for anyone else, we always …
> Add cookie for GOVUK-ABTest-Benchmarking

- vcl_templates/www.vcl.erb
The Benchmarking will be completed at the end of Sunday 26th March. Once this is completed, we will remove the code we used to track users' mouse use.
https://trello.com/c/CPKWJ6t4/552-remove-heatmap-tracking
> Remove mouse tracking

- vcl_templates/assets.vcl.erb
This will be used to store logs of the requests from the tracking
Javascript.
> Serve an empty response direct from Fastly

- vcl_templates/assets.vcl.erb
This message was returned to the user. Revert it to "OK"
> Fix status message for static analytics endpoint

- vcl_templates/tldredirect.vcl.erb
The 1 hour max-age introduced in #26 seems to be fine. This
commit increases that to 2 years (63072000 seconds), as a further step
outlined in #14.
> Bump TLD redirect HSTS max-age to 2 years

- vcl_templates/assets.vcl.erb
Without this change, browsers warn that they’re not allowed to use the
response. Our code isn’t using the response anyway, but we shouldn’t be
throwing Javascript errors. Returning this header stops those errors
being raised.
> Send a CORS header with the analytics response

- vcl_templates/assets.vcl.erb
Update assets template to use new S3 mirror instead of mirror1.
There are a few changes specific for S3:
- Depending on how the bucket is configured, the backend probe request
needs to point to the directory where the content is located
- S3 does not set cache headers by default, we need to override the default TTL and add
header based on previous Nginx mirror configuration
- Requests need to be rewritten to match location in the bucket
- S3 errors need to serve static error page
> Enable assets S3 mirror

- vcl_templates/www.vcl.erb
Update www template to use new S3 mirror instead of mirror1.
There are a few changes specific for S3:
- Depending on how the bucket is configured, the backend probe request
needs to point to the directory where the content is located
- S3 does not set cache headers by default, we need to override the default TTL and add
header based on previous Nginx mirror configuration
- Requests need to be rewritten to match location in the bucket and add file extension
if it does not exist in the request, similar to try_files configuration in Nginx
- S3 errors need to serve static error page
> Enable www S3 mirror

- vcl_templates/www.vcl.erb
This adds dynamic template rendering for both the setting of the request headers used for A/B tests and for the setting of the cookies.
Configuration for A/B tests is now done in [`fastly-configure`](https://github.com/alphagov/fastly-configure). Example config can be seen in [this PR](https://github.com/alphagov/fastly-configure/pull/21)
Using Fastly dictionaries was investigated to some length and we got it working, however it would have required a much larger vlc template with more generalised test names (test_0, test_1, etc)
https://trello.com/c/jsmd99NV/89-prototype-a-b-testing-configuration-changer
> Add extra templating for ab testing

- vcl_templates/www.vcl.erb
We can now use a hybrid system which allows us to enable/disable tests as well as change certain settings without having to deploy Fastly each time.
[Dictionaries PR](https://github.digital.cabinet-office.gov.uk/gds/cdn-configs/pull/124)
[Fastly Config PR](https://github.com/alphagov/fastly-configure/pull/25)
https://trello.com/c/HOV2ChJ9/104-simplify-a-b-test-cdn-configuration
> Change VCL templating

- vcl_templates/www.vcl.erb
In this PR:
- increase the number of users that see the new navigation on Education content to 50%, so we can increase the pool of users that will try the new A/B test below;
- add the header and cookie to all users that will be seeing the existing EducationNavigation A/B test. We split those users into 2 groups: 50% will see things unchanged (control) and the other 50% will see the new pattern, a blue box. The cookie is set to expire after 45 days, which means that by then we would have either removed the blue box or add it to everyone.
Trello: https://trello.com/c/S5jp2jih/179-setup-technical-implementation-for-a-b-testing-the-blue-box
When both dependencies are merged, we can then go ahead and deploy this. The changes to the A/B testing gem will allow for verbose variant names.
> Add blue box ab test

- vcl_templates/www.vcl.erb
In this PR:
- increase the number of users that see the new navigation on Education content to 50%, so we can increase the pool of users that will try the new A/B test below;
- add the header and cookie to all users that will be seeing the existing EducationNavigation A/B test. We split those users into 2 groups: 50% will see things unchanged (control) and the other 50% will see the new pattern, a blue box. The cookie is set to expire after 45 days, which means that by then we would have either removed the blue box or add it to everyone.
Trello: https://trello.com/c/S5jp2jih/179-setup-technical-implementation-for-a-b-testing-the-blue-box
> Blue box ab test

- vcl_templates/assets.vcl.erb
Match www and assets configuration by adding the Fastly-Backend-Name
header to Assets responses. This header allows us to monitor which
backend is serving each response.
> Add Fastly-Backend-Name header on all Assets responses

- vcl_templates/www.vcl.erb
We now check for any existing a/b tests in the config yaml file.
> Guard against no running a/b tests

- vcl_templates/www.vcl.erb
This reverts commit 5cc21d7db46b305f89301af1a5fe67a0572cce68.
The A/B test is now complete and we are rolling out blue boxes to all
accordion pages to users in the new navigation.
More details here: https://github.com/alphagov/collections/pull/360
Trello: https://trello.com/c/U50vnFY8/36-navbeta-going-100-with-the-blue-box
> Revert "Add blue box A/B test for users in new NavigationTest"

- vcl_templates/www.vcl.erb
This commit allows us to rollout the EducationNavigation A/B test to Childcare and Parenting navigation pages. By visiting those pages, users will be automatically assigned to the B variant of that A/B test, which means they will be able to see the new navigation across both navigation pages and content pages.
Note: the taxonomy isn't live yet, but once it's published this will start working. It's safe to deploy this change because it doesn't affect any other branch.
Trello: https://trello.com/c/Sa4FrnW2/66-update-cdn-configs-to-include-parenting-childcare-root-taxon
This has been tested in staging:
- deploy link: https://deploy.staging.publishing.service.gov.uk/job/Deploy_CDN/162/console
- branch in fastly-configure: https://github.com/alphagov/fastly-configure/compare/test-cdn-config-bra …
> Add cookie on childcare and parenting pages

- vcl_templates/www.vcl.erb
https://trello.com/c/WT9haiUu/59-remove-all-remaining-parts-of-education-navigation-ab-test-logic
The education navigation AB test is being removed.
This PR reverts https://github.com/alphagov/govuk-cdn-config/pull/29
DNM because we need to deploy this and other PRs in a specific order
> Remove Education nav AB test config

- vcl_templates/assets.vcl.erb
This mimics the behaviour of the www service and might assist in
debugging the issue where Word documents are delivered to the browser
as plaintext.
Copied from https://github.com/alphagov/govuk-cdn-config/blob/master/vcl_templates/www.vcl.erb#L234
> Add the backend name to response header for assets service

- vcl_templates/www.vcl.erb
This extra header is [used by supporting browsers to preload the font](https://www.w3.org/TR/preload/#early-fetch-of-critical-resources) (our biggest asset). This means that the browser can load the file in parallel with the other work to load the page, it doesn't have to wait before the DOM is loaded. This is an experiment to see if it makes a difference in the performance of GOV.UK.
Initial tests on staging are inconclusive, but it's hard to test this because staging doesn't have an SSL certificate so our speed test software can't look at it. I intend to run this on GOV.UK for a few
weeks and use Speedcurve to monitor differences.
If we were going to use this, we'd obviously have to figure out a way to make sure this URL doesn't go out of date. It hasn't changed in 4 years, but might …
> Experiment with preloading the font

- vcl_templates/www.vcl.erb
Added a request header containing the TLS version number for requests to the Licensify app
(This is so we can block requests with TLS versions below 1.2 for payment security reasons)
> Add TLS header for Licensify requests

- vcl_templates/www.vcl.erb
This preloading of the font has been in place since Feb 1st (https://github.com/alphagov/govuk-cdn-config/pull/64). This commit rolls it back because:
- We are likely to be start implementing a different font loading strategy, which makes use of WOFF and WOFF2 compression. At this point we can't preload the font because this would likely result in extra downloads (all users would get the WOFF2, even if they won't use it).
- Chrome seems to be loading the font twice. This could be caused by the absence of the `crossorigin` in the preload header, but we don't know for sure.
> Remove font preloading

- vcl_templates/www.vcl.erb
Reverts alphagov/govuk-cdn-config#65. This was tested on staging but doesn't seem to work. More investigation is required.
cc @PeteLeaman
> Revert "Add TLS header for Licensify requests"

- vcl_templates/www.vcl.erb
Added a request header containing the TLS version number for requests to the Licensify app
(This is so we can block requests with TLS versions below 1.2 from submitting, for payment security reasons)
>  Add TLS header for Licensify requests

- vcl_templates/www.vcl.erb
This is only temporary, so we're using a synthetic response at the CDN layer rather than getting Jisc to made DNS changes, or adding the relevant information to both static and routing to allow us to serve up a real static file.
> Add CloudPiercer verification

- vcl_templates/www.vcl.erb
Previous details in #69 were for the whole gov.uk domain space. CP's verification didn't follow the http://gov.uk/ → https://gov.uk/ → https://www.gov.uk/ redirect path, so this is limited to just www.gov.uk.
> Update CloudPiercer verification

- vcl_templates/www.vcl.erb
It turns out that Varnish caches the HTTP basic auth headers which means after the first authentication, everything is wide open. This locks down the integration CDN to the same IP addresses as staging. Other departments will continue to access integration via origin which will have HTTP basic auth.
> Add IP-based filtering to integration CDN

- vcl_templates/www.vcl.erb
Fix typo in https://github.com/alphagov/govuk-cdn-config/pull/78
> Typo fix on basic_authentication config key

- vcl_templates/www.vcl.erb
https://trello.com/c/vX7ZC4fb/673-work-out-why-some-paths-return-an-error-message-when-using-the-integration-cdn
After some advice from Fastly we think this might solve the failing (401) requests to origin.
Also tidy up whitespace in healthcheck headers.
Relevant also to a typo fix here https://github.com/alphagov/cdn-configs/pull/76
> Forward basic auth header to origin when present

- vcl_templates/www.vcl.erb
This commit adds basic auth to the integration CDN with the same credentials as origin. It also removes the IP blocking to allow people outside the GDS network to access it, bringing it into line with integration origin.
> Add basic auth to and open integration

- vcl_templates/www.vcl.erb
Safari doesn’t like the realm name with spaces in it, and it’s not necessary.
> Remove basic auth realm for integration

- vcl_templates/www.vcl.erb
This introduces a report-only Content Security Policy (CSP) for GOV.UK.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
> The HTTP Content-Security-Policy response header allows web site administrators to control resources the user agent is allowed to load for a given page. With a few exceptions, policies mostly involve specifying server origins and script endpoints. This helps guard against cross-site scripting attacks (XSS).
I designed the policy in government-frontend, this being the commented source:
```
*.publishing.service.gov.uk
"default-src https 'self' *.publishing.service.gov.uk;",
pixel), and publishing domains.
"img-src 'self' www.google-analytics.com *.publishing.service.gov.uk;",
domains, and 2 scripts:
"script-src 'self' …
```
> Experiment with CSP

- vcl_templates/www.vcl.erb
This was introduced in https://github.com/alphagov/govuk-cdn-config/pull/84. We've ran it for a bit on integration and we'll now analyse the data. Reverting now to avoid conflicts with https://github.com/alphagov/govuk-cdn-config/pull/86.
https://trello.com/c/ml5fQQxS
> Remove CSP reporting header again

- spec/test-outputs/apt-integration.out.vcl
- spec/test-outputs/apt-production.out.vcl
- spec/test-outputs/apt-staging.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/performanceplatform-integration.out.vcl
- spec/test-outputs/performanceplatform-production.out.vcl
- spec/test-outputs/performanceplatform-staging.out.vcl
- spec/test-outputs/performanceplatform_admin-integration.out.vcl
- spec/test-outputs/performanceplatform_admin-production.out.vcl
- spec/test-outputs/performanceplatform_admin-staging.out.vcl
- spec/test-outputs/performanceplatform_stagecraft-integration.out.vcl
- spec/test-outputs/performanceplatform_stagecraft-production.out.vcl
- spec/test-outputs/performanceplatform_stagecraft-staging.out.vcl
- spec/test-outputs/servicegovuk-integration.out.vcl
- spec/test-outputs/servicegovuk-production.out.vcl
- spec/test-outputs/servicegovuk-staging.out.vcl
- spec/test-outputs/tldredirect-integration.out.vcl
- spec/test-outputs/tldredirect-production.out.vcl
- spec/test-outputs/tldredirect-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/vcl_generation_spec.rb
We intend to do some refactoring of the code in this repo. To make sure that we don't unintentionally change the VCL that we send to Fastly, this commit adds a test that generates the VCL for each environment and service combination, and checks that against the VCL that we know is good.
You can use `REGENERATE_EXPECTATIONS=1 bundle exec rspec` to regenerate the files. That's useful if you've made changes that you know are fine.
https://trello.com/c/y6MIgxjp
> Test VCL against previously generated files

- configure_bouncer
- deploy-bouncer.sh
This imports the code used to deploy the Fastly configuration for Bouncer. The deploys are triggered (nightly) from Jenkins, which is updated in https://github.com/alphagov/govuk-puppet/pull/8598.
The code is a straight copy-paste from alphagov/cdn-configs:
https://github.com/alphagov/cdn-configs/blob/6f45502ff2ef55c7c19870f0870404f1c318f53f/fastly/configure_bouncer
The code at present doesn't conform to many of the standards we have on GOV.UK, this will be fixed in follow up PRs. The goal of this PR is just to make the CDN deploy system easier to understand by colocating the code.
Tested successfully with:
https://deploy.blue.production.govuk.digital/job/Bouncer_CDN/112/console
Part of paying down CDN deploy tech debt: https://trello.com/c/y6MIgxjp
> Import code to deploy bouncer

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
These cookies were used for the JS/No-JS experiment (https://github.com/alphagov/govuk-cdn-config/pull/39). We're removing the experiment in https://github.com/alphagov/frontend/pull/1747 and https://github.com/alphagov/govuk-puppet/pull/8643.
> Remove Javascript tracking cookies

- lib/csp.rb
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
Follow up to https://github.com/alphagov/govuk-cdn-config/pull/94. See commits for details. The changes are all based on violations reported to Sentry in https://sentry.io/govuk/govuk-frontend-csp.
I've tested the resulting policy with https://csp-evaluator.withgoogle.com
> Iterate Content Security Policy

- lib/csp.rb
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
Follow up to https://github.com/alphagov/govuk-cdn-config/pull/96.
`:data` should be `data:` because it's a URL and not a Ruby symbol.
https://sentry.io/govuk/govuk-frontend-csp/issues/874477487
Captain Hindsight: I should've tested the CSP with https://cspvalidator.org too, because that correctly identifies this error.
[Test it yourself](https://cspvalidator.org/#headerValue%5B%5D=default-src+https+'self'+*.publishing.service.gov.uk%3B+img-src+'self'+data%3A+www.google-analytics.com+*.publishing.service.gov.uk%3B+script-src+'self'+www.google-analytics.com+ssl.google-analytics.com+*.publishing.service.gov.uk+'sha256-G29%2FqSW%2FJHHANtFhlrZVDZW1HOkCDRc78ggbqwwIJ2g%3D'+'sha256-%2B6WnXIl4mbFTCARd8N3COQmT3bJJmo32N8q8ZSQAIcU%3D'+'unsafe-inline'%3B+style-src+'self'+*.publishing.service.gov.uk+'u …
> Fix CSP font-src source declaration

- lib/csp.rb
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
This was missed in https://github.com/alphagov/govuk-cdn-config/pull/96, which only allowed `connect-src` from Verify. We also use JSONP, which is governed by script-src.
[CSP validator](https://cspvalidator.org/#headerValue%5B%5D=default-src+https+'self'+*.publishing.service.gov.uk%3B+img-src+'self'+data%3A+www.google-analytics.com+*.publishing.service.gov.uk%3B+script-src+'self'+www.google-analytics.com+ssl.google-analytics.com+*.publishing.service.gov.uk+'sha256-G29%2FqSW%2FJHHANtFhlrZVDZW1HOkCDRc78ggbqwwIJ2g%3D'+'sha256-%2B6WnXIl4mbFTCARd8N3COQmT3bJJmo32N8q8ZSQAIcU%3D'+www.signin.service.gov.uk+'unsafe-inline'%3B+style-src+'self'+*.publishing.service.gov.uk+'unsafe-inline'%3B+font-src+data%3A+*.publishing.service.gov.uk%3B+connect-src+'self'+www.google-analytics.com+*.publishing.servic …
> Allow script loading from Verify

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We've collected data in Sentry on CSP and we're going to analyse and fix the reported violations.
Keep CSP on staging & integration for testing purposes.
https://sentry.io/govuk/govuk-frontend-csp
> Don't use CSP on production

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/bouncer.vcl.erb
- vcl_templates/www.vcl.erb
Due to the way transitioned domains redirect to paths on GOV.UK (usually
department pages), autodiscover lookups can also happen at paths other
than the route.
> Handle autodiscover paths that aren't at the root

- README.md
- deploy-dictionaries.sh
- jenkins.sh
- spec/vcl_generation_spec.rb
We've renamed this repo:
https://github.com/alphagov/govuk-cdn-config-secrets
> Rename cdn-configs repo

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/bouncer.vcl.erb
- vcl_templates/www.vcl.erb
We use a synthetic 404 response for handling requests for `autodiscover.xml` paths (see #86), but the way these are handled isn't optimal:
* It gets treated as a generic error, which is assumed to be due to a backend being unavailable, and gets retried.
* The response sent back implies that an error occurred.
This change uses a custom HTTP status to skip retrying, and provides a more user-friendly (and correct) response body.
> Improve handling for forced-404 responses

- deploy_service
- lib/deploy_service.rb
- spec/deploy_service_spec.rb
This makes it consistent with "deploy bouncer" and "deploy dictionaries", and with the shell scripts.
https://trello.com/c/y6MIgxjp
> Use consistent naming for "deploy service" task

- lib/deploy_dictionaries.rb
- spec/deploy_bouncer_spec.rb
- spec/deploy_dictionaries_spec.rb
- spec/deploy_service_spec.rb
This adds some tests for the bouncer and dictionary deploy code, which is possible after https://github.com/alphagov/govuk-cdn-config/pull/114 and https://github.com/alphagov/govuk-cdn-config/pull/115.
The tests themselves aren't particularly nice, but they exercise most of the functionality. During refactoring we should make the tests nicer as well.
https://trello.com/c/y6MIgxjp
> Increase test coverage

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/vcl_generation_spec.rb
- vcl_templates/assets.vcl.erb
- For AWS migration in staging, we switch around the asset handling
routes on the level of Fastly
- The new default is AWS, holding the frontends, which special cases of
the asset-manager and whitehall-frontend still remaining in Carrenza
solo: @schmie
> Changing CDN configuration for asset-origin around

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- vcl_templates/assets.vcl.erb
As part of the AWS migration of the frontends where the asset manager and whitehall frontend are left in Carrenza, there is a need to configure fastly to route any common and whitehall assets to the Carrenza load balancer which was setup to handle assets as part of the AWS migration. This change will allow us to use one less CDN backend and not exceed the 5 CDN backend limit that fastly has.
1. Change the `if` statement to route all common and whitehall assets to the Carrenza Assets load balancer.
2. delete the whitehall CDN backend.
> route whitehall assets via assets load balancer

- configs/dictionaries/active_ab_tests.yaml
We now have the necessary data for this test, so we can disable it.
> Disable related links AB1 test

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/vcl_generation_spec.rb
- vcl_templates/assets.vcl.erb
[DO NOT MERGE]: While this is safe to merge, deployment would break Fastly ATM - so keep it out of the loop for now.
- During the migration the asset-manager and whitehall assets remains in Carrenza
environments close to Publishing-API and Whitehall, whereas frontends
are located in AWS.
- Assets are served both from asset-manager and frontends, so we need to
separate the traffic for Carrenza and AWS
- We have decided to put the logic to do this into Fastly.
- We filter assets paths with regexp
- Carrenza-side this requires creation of a new nginx proxy
assets-carrenza in order to be able to turn off the cache boxes
post-migration
solo: @schmie
> Add logic to re-route asset traffic

- spec/test-outputs/tldredirect-integration.out.vcl
- spec/test-outputs/tldredirect-production.out.vcl
- spec/test-outputs/tldredirect-staging.out.vcl
- vcl_templates/tldredirect.vcl.erb
This commit sets the `preload` flag for the `Strict-Transport-Security` HTTP header. This signals to browsers that the domain should be added to the HSTS preload list that is shipped with most modern browsers.
> Set preload for Strict-Transport-Security header

- configs/dictionaries/active_ab_tests.yaml
We have now collected the necessary data for this test, so it can be disabled.
> Disable related links AB2 test

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
After migration of the cache clearing service, we do require the
backends in AWS to be able to purge entries in Fastly cache
solo: @schmie
> Add AWS NAT Gateway Elastic IPs to purge whitelist

- configs/dictionaries/active_ab_tests.yaml
We have now collected the necessary data for this test, so it can be disabled.
> Disable related links AB3 test

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
All cookies on GOV.UK should be secure and not setting ABTest cookies as secure looks to have been an oversight when AB tests were added https://github.com/alphagov/govuk-cdn-config/pull/13
> Set ABTest cookies to secure

- spec/test-outputs/datagovuk-integration.out.vcl
- spec/test-outputs/datagovuk-production.out.vcl
- spec/test-outputs/datagovuk-staging.out.vcl
- vcl_templates/datagovuk.vcl.erb
Add boilerplate vcl and include ip whitelist for cache purging for
data.gov.uk.
Associated [PR 8904](https://github.com/alphagov/govuk-puppet/pull/8904) in puppet.
> Add vcl for data.gov.uk

- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- vcl_templates/assets.vcl.erb
Context
Documentation suggests that a manual purge should be done from a cache machine
and this is not possible from AWS as the egress ips are not in the whitelist
(Doc Link: https://docs.publishing.service.gov.uk/manual/cache-flush.html)
Decision
Add the Elastic IPs used for cache in AWS to the VCL config.
> Add AWS Elastic IPs to the purge_ip_whitelist for assets

- configs/dictionaries/active_ab_tests.yaml
We have now collected the necessary data for this test, so it can be disabled.
> Disable Related Links v4 A/B test

- configs/dictionaries/active_ab_tests.yaml
We're experiencing an incident where finders are struggling.  We want to
turn this off for a bit to see if this relieves pressure.
> Disable AB test

- configs/dictionaries/active_ab_tests.yaml
Trello: https://trello.com/c/VYMcypuO
Reverts: #147
The search improvements made as a result of the incident on 8th April have been stable for a day,
so we think it’s safe to turn the test back on.
> Re-enable FinderAnswerABTest

- spec/test-outputs/apt-integration.out.vcl
- spec/test-outputs/apt-production.out.vcl
- spec/test-outputs/apt-staging.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/performanceplatform-integration.out.vcl
- spec/test-outputs/performanceplatform-production.out.vcl
- spec/test-outputs/performanceplatform-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/apt.vcl.erb
- vcl_templates/assets.vcl.erb
- vcl_templates/bouncer.vcl.erb
- vcl_templates/performanceplatform.vcl.erb
- vcl_templates/www.vcl.erb
After a discussion with Fastly Support we learnt that we don't have the
ability to purge individual URLs from Fastly via the web UI because of
our VCL configuration. We actually return a 403 as the requests are not
in the allowed list.
Fastly support suggested that we change our return of error 403 to
instead set a head a header that authentication is required. Without a
valid token to authenticate these will deny the request and return a
message that authentication is needed.
> Restore ability to purge URLs by Fastly web UI

- spec/test-outputs/www-integration.out.vcl
- vcl_templates/www.vcl.erb
We have a problem where backend apps in integration can't access other integration services via the Internet because they require authentication. Instead of requesting the apps pass in the username/password we can allow access based on their IP address and request basic authorization from everyone else.
[Zendesk Ticket](https://govuk.zendesk.com/agent/tickets/3682605)
> Allow bypassing basic authorisation if allowed IP address

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/vcl_generation_spec.rb
- vcl_templates/mirror.vcl.erb
There is no need for:
1. blacklisting IPs because only few IPs are allowed to connect to this
fastly service by default
2. AB tests because no such tests are needed on the mirror fastly service
1. remove blacklist ips section
2. remove import of AB tests
> Optimize mirror vcl

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Paired with @koetsier on this.
I would appreciate thoughts on this (implementation details, concerns/risks, in general and in response to the P1 issue).
At the moment we only cache GET/HEAD requests.
Now we'll cache any request, if that request returns a 404 (Not Found) or 405 (Method Not Allowed).
Note that administration/publishing applications don't sit behind this cache, so (e.g.) requests to create documents won't be affected by this change.
If a DELETE request is made to a page on the gov.uk website - for the most part not permitted - this should return a 405.
We then cache this response, so future DELETE requests to the same resource will not reach the origin until the default Time-to-live (TTL) for the cached object expires (at the moment, the default TTL is 5000 seconds).
This …
> Cache non-GET/HEAD requests with 404/405 responses

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- vcl_templates/mirror.vcl.erb
The `mirror` fastly service is used to test the mirrors for `www` fastly service.
Hence, the `mirror` fastly service will have the same vcl as the `www` fastly service except for:
1. clients should be in the whitelist to access the `mirror` fastly service.
We test the mirrors after deploying the `mirror` fastly service by going into the fastly management console and change the active vcl for the service so that it points to an unreachable origin and therefore the service will fallback to mirrors.
1. copy the future www template vcl to be tested to mirror template vcl and modify the template vcl to restrict client for all environments rather than staging and integration only.
> new production and staging mirror fastly service

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
New gov.uk mirror redesign:
If the www origin backend is down, fastly will use stale cache as before.
If object is not in cache, the S3 mirror bucket in London is used. If this fails, the
replica S3 mirror bucket in Ireland is used. As last resort,
we use the Google Cloud Storage bucket in multi-region EU.
Other changes:
1. we no longer have a sick backend because it is pointless as we keep the grace period to 24 hours regardless, so the example previously followed: https://book.varnish-software.com/3.0/Saving_a_request.html#example-evil-backend-hack no longer applies. Confirmed with fastly that this is fine.
2. if the backend is origin and we encounter an error from the origin, we try to serve stale too.
1. re-write the www vcl config to accommodate the 3 mirror buckets and removal of …
> New www and assets vcl mirror

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/mirror.vcl.erb
- vcl_templates/www.vcl.erb
There is a fallback to mirrors if page not found on origin website and if the page is not found in the mirrors, the mirror response body is sent to the client. We actually want the response body to be the govuk customize message.
If an object is 404 and comes from the mirrors, send the govuk 404 custom response body.
> if object is 404, serve govuk 404 body rather than backend 404 body

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
This PR adds a new header `Govuk-Use-Recommended-Related-Links` to the `www` vcl. This header is used by `government-frontend` to determine whether to show the new recommended related links, or by its absence to default back to existing related links.
We're adding this as a separate header to the CDN to enable quick rollback of the auto-generated recommended related links to existing related links for our users.
> Add recommended related links header to www vcl

- lib/govuk_fastly.rb
- spec/deploy_bouncer_spec.rb
- spec/deploy_dictionaries_spec.rb
- spec/deploy_service_spec.rb
It looks like the Fastly API no longer supports username/passwords for authentication.
[Trello Card](https://trello.com/c/19Gc1KkK/1109-fix-auth-issue-for-cdn-deploy-bouncer-configs-job-in-prod)
> Switch to API key based authentication

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/mirror.vcl.erb
- vcl_templates/www.vcl.erb
When the origin application is sick, the fastly fetches the content from the first mirror. If the first mirror does not find it, we go through the other mirrors. If the last mirror, does not have it, fastly should return a custom 503 govuk error. Unfortunately, fastly is returning a 404 `not found` if the first mirror does not have it.
This is due to the fact that the code for checking mirror response http code is too late in the order of things in vcl_fetch, needs to go higher up
1. move the code block to check response code of mirrors to higher up in vcl_fetch to get the behaviour that we want
2. modify that code block to try all mirrors before erroring.
> fix 404 page still served from mirror if origin fails

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/performanceplatform-integration.out.vcl
- spec/test-outputs/performanceplatform-production.out.vcl
- spec/test-outputs/performanceplatform-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/mirror.vcl.erb
- vcl_templates/performanceplatform.vcl.erb
- vcl_templates/www.vcl.erb
It looks like Fastly have updated their IP addresses: https://deploy.publishing.service.gov.uk/job/Check_CDN_IP_Ranges/1444/console
> Update Fastly IPs

- configs/dictionaries/ab_test_expiries.yaml
We've launched a new test, and the name needs to be updated here.
> Correct test name

- configs/dictionaries/active_ab_tests.yaml
This PR sets the landing page test to active, which I think is needed to deploy and be able to check it has been set up properly.
Traffic won't actually start being sent to any variants until we've implemented the logic in Collections and have adjusted the percentages to direct a proportion of traffic to B.
> Make landing page AB test active

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Any paths under our three `register-to-vote` base paths are not
neccessary and we can safely normalise to the base path.
Similarly, we don't need the querystrings on these paths and allowing
them just leads to more needless requests to origin.
[Trello](https://trello.com/c/cpi5iw7T/846-temporarily-strip-cache-bust-string-on-register-to-vote-in-our-vcl)
> Remove querystrings and sub paths from register-to-vote

- README.md
The README contains various links to scripts in the repo itself. These
have `/blob/master` prepending them, but github automatically adds the
segments needed for the current branch.
> Remove spurious segments from links to scripts

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
This reverts commit f90abeaba4fd91ebf117b05c5984d5bebf4f8713.
This allows things like cache-busting strings to work again and removes some "weird" from the world.
> Stop special treatment of register-to-vote

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/mirror.vcl.erb
- vcl_templates/www.vcl.erb
This was set so that we can more easily track TLS version support in GA. The number of users who have interacted with the related banner we set in static is down to 0.02% of total users, and down from 19,664 to only 4,272 in one year.
> Remove setting TLSversion cookie

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
This reverts commit 689fe7eb4c800ac9fb4393c150133d1c3285389a.
We found a bug in this code that prevents FASTLYPURGE requests
from working as expected. In the vcl_hash we include the request
method in the hash key we use to store and lookup objects in the cache.
This works fine for GET/HEAD/POST requests because we can cache
the responses to these requests as separate objects (a post response
might be different to a get response).
However, it means that FASTLYPURGE requests lookup items in the cache
using FASTLYPURGE as part of the hash, preventing purges from working
as expected.
Rather than attempting to patch this by adding more complexity to the
VCL, we've decided to approach the problem we were trying to solve in
a different way.
Thanks to @kevindew for working on this with me. …
> Remove VCL code for caching non-GET/HEAD requests

- spec/test-outputs/apt-integration.out.vcl
- spec/test-outputs/apt-production.out.vcl
- spec/test-outputs/apt-staging.out.vcl
- vcl_templates/apt.vcl.erb
For the migration to AWS we're going to use https to connect to
the apt LB.
> Change apt backend connection port from 80 to 443

- spec/fixtures/_multivariate_tests.vcl.erb.out
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/_multivariate_tests.vcl.erb
- vcl_templates/www.vcl.erb
There are two parts to this:
1. Don't set the A/B header (which assigns them to a bucket)
2. Don't set the A/B cookie (which keeps them in the same bucket)
I think step 1 is strictly speaking unnecessary, as it doesn't involve cookies.  But we probably don't want people to get a random bucket on every page view, so it's good to do.
If someone consents, then on their next page load they'll be bucketed for each active A/B test.
---
[Trello card](https://trello.com/c/FOxkorss/1356-update-a-b-testing-to-work-with-new-cookies-policy)
> Disable A/B tests if the user has not consented to analytics

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/vcl_generation_spec.rb
- vcl_templates/assets.vcl.erb
**PLEASE TEST THIS IN STAGING THOROUGHLY BEFORE MOVING TO PRODUCTION**
now that asset-manager lives in AWS and all assets are in AWS,
we need to route all assets to AWS without any exception.
Associated [PR](https://github.com/alphagov/govuk-cdn-config-secrets/pull/111)
> remove carrenza assets cdn route

- ab_tests/ab_tests.yaml
- configs/dictionaries/ab_test_expiries.yaml
- configs/dictionaries/active_ab_tests.yaml
- configs/dictionaries/learning_to_rank_model_ab_test_percentages.yaml
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
This replaces the finder-frontend reranker feature flag with an AB test for comparing reranker models.
Should be merged and deployed after search-api and finder-frontend.
https://trello.com/c/1EjO05Dj/1333
> Add Learning To Rank Model AB Test

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
To make sure that these pages are as cached as they possibly can.
Similar to #213.
> Strip query strings on coronavirus pages

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Avoiding the need for `re.group.0` as `req.url.path` contains the path without any query parameters.
> Fix coronavirus path regex

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We're anticipating a lot of traffic and want to make sure users can find what they need.
> Add coronavirus link to error pages

- ab_tests/ab_tests.yaml
- configs/dictionaries/ab_test_expiries.yaml
- configs/dictionaries/active_ab_tests.yaml
- configs/dictionaries/showpartsinresultsabtest_percentages.yaml
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
See also https://github.com/alphagov/finder-frontend/pull/2025
We shouldn't deploy this until the "HTML attachments as parts" work is deployed.
---
[Trello card](https://trello.com/c/sDDx1mn8/1463-display-parts-in-search-results-ab-test)
> Add parts-in-results A/B test

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We added this when we were anticipating high levels of traffic on these pages, but it causes confusion when trying to view the latest version of these pages.
> Remove query string stripping of coronavirus pages

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- vcl_templates/assets.vcl.erb
The code for this was removed from static in
https://github.com/alphagov/static/pull/2152 and thus this endpoint is
not used anymore. The 802 status response in this host was only used by
this endpoint so can also be removed.
> Remove /static/a endpoint

- README.md
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/performanceplatform-integration.out.vcl
- spec/test-outputs/performanceplatform-production.out.vcl
- spec/test-outputs/performanceplatform-staging.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/bouncer.vcl.erb
- vcl_templates/mirror.vcl.erb
- vcl_templates/performanceplatform.vcl.erb
- vcl_templates/www.vcl.erb
This updates the terminology used in this repo to reflect GDS guidance:  https://docs.google.com/document/d/1LpBxQ9zJZp7c4eygTMWBQzGNtb9hMh-2SEV3jOlLLxY/edit?ts=5f10079a#
It then updates the assets, bouncer, and performanceplatform services to allow them to accept the denylist for ip addresses so that IP's can be banned from all services rather than just one and cause confusion.
There is a similar PR open for govuk-cdn-config-secrets: https://github.com/alphagov/govuk-cdn-config-secrets/pull/129 and there will be a puppet PR to allow updating the dictionaries.
> Update terminology and allow banning IP addresses in more services

- vcl_templates/bouncer.vcl.erb
Since bouncer is handled differently to the other VCL services with a
different deployment process this wasn't easy to apply consistently. I'm
removing this for now and we can consider adding it back in were we to
establish a point of need for it.
> Revert ip banning at bouncer

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We are anticipating increased traffic to this page and need to ensure
that is served from cache as much as possible.
[Trello](https://trello.com/c/3YPZiLhl/2091-strip-querystrings-from-eat-out-to-help-out-page)
> Remove query params from requests to Eat Out to Help Out Scheme page

- vcl_templates/bouncer.vcl.erb
There are so many requests, I'm hoping this will reduce the
number. I'm not sure about the usefulness of the Fastly healthcheck
for bouncer, as I'm not sure what it should do differently if the
healthcheck fails...
> Set a 30 second interval for bouncer healthchecks

- vcl_templates/bouncer.vcl.erb
As it doesn't exist, at least now Bouncer is running in AWS. I believe
this also removes the need for a healthcheck, since there's only one
backend to use, you don't need the healthcheck to know when to
failover.
> Remove the disaster recovery backend for bouncer

- vcl_templates/bouncer.vcl.erb
As Fastly/Varnish don't like it being removed. A dynamic backend must
have a probe, and the backend must be dynamic to use a hostname.
This is adding back the probe, but further increasing the interval
since I don't think there's much value in sending probe requests very
frequently.
> Restore the Bouncer backend probe

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Reverts alphagov/govuk-cdn-config#276
The scheme is over now so we don't need to be striping query strings anymore.
> Revert "Remove query params from requests to Eat Out to Help Out Scheme page"

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We want to show an accounts-related header on /transition and in the
transition checker, with either sign in or sign out links.
A/B testing feels like a slightly weird way to do this, because it's
not an A/B test, but it is an established technique we have for
displaying variants of GOV.UK pages which plays nicely with caching.
We should revisit this when we address the larger topic of how to be
logged in across GOV.UK (rather than logged in to one app).
---
The cookie was introduced in https://github.com/alphagov/finder-frontend/pull/2263
---
[Trello card](https://trello.com/c/uV2ZSNzH/376-put-the-user-in-an-a-b-bucket-based-on-the-presence-of-the-accounts-session-cookie)
> Put the user in an A/B bucket based on whether they're logged in

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
https://trello.com/c/7qWgBlA7/617-investigate-handling-actiondispatchremoteipipspoofattackerror
Previously a user could manually specify these headers, which could
result in a spoofing error for Rails apps trying to detect the client
IP address [1]. Although the use of the headers by the end user is
valid, we can't trust and shouldn't care about any proxies that the
request has been through before reaching our network. This ensures
the proxy headers are reset before the request continues.
Trying this manually (before/after) shows that:
- Fastly does not have a default value for the Client-IP header, so
it's consistent to enforce that it is unset.
- Fastly pre-populates X-Forwarded-For with the "actual" client IP,
so we should preserve that (but ignore any pre-existing header).
Note that …
> Reset proxy headers to avoid spoofing alerts

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
7e78be3 didn't work for two reasons: firstly, accidentally omitted the vcl_synth subroutine; secondly, Fastly doesn't support vcl_synth() anyway so we need to use vcl_error().
Use vcl_error() to allow synthesising 302 responses from within vcl_recv. We're using this in alphagov/govuk-cdn-config-secrets#131.
Co-authored-by: @OllieJC
Tested: tested positive and negative cases in staging
See also alphagov/govuk-cdn-config-secrets#132
> Fix ability to synthesise redirects from vcl_recv.

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
The (per-environment) config item `private_extra_code_in_vcl_recv` allows inserting snippets of VCL from the private govuk-cdn-config-secrets repo into `vcl_recv()`.
Allow this to be used in any environment rather than just staging, now that it's been tested in staging.
Also be a bit more flexible by ignoring the case when `private_extra_code_in_vcl_recv` is not specified in the config, instead of failing.
Follows on from #307 and alphagov/govuk-cdn-config-secrets#132.
Test/rollout plan: rspec is passing. Will test in staging once merged, before rolling to prod.
> Allow private VCL code snippets in all environments.

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
To enable request tracing for GOV.UK we need to set a request id at the CDN so we can trace requests through all layers of GOV.UK
> Set GOV.UK-Request-Id to allow request tracing

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
When a user visits /find-coronavirus-local-restrictions we will remove all query parameters except for the postcode query parameter, which we will normalise (lowercase, restrict to alphanumerics). See [Fastly Fiddle for demonstration](https://fiddle.fastlydemo.net/fiddle/35784abb).
> Parse and normalise URL query for local restrictions page

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Trello: https://trello.com/c/sCaPVTCo/997-14th-december-follow-up-work
This removes the postcode formatting for requests to
/find-coronavirus-local-restrictions in favour of a JavaScript one done
within the collections app: https://github.com/alphagov/collections/pull/2156
The switch to a JavaScript approach was chosen so that the code can be
kept with the app (with tests) and to improve user experience (this CDN one will
produce confusing outcomes for invalid postcodes). The trade-off for the
JS one is that is less aggressive in it's formatting and, by nature of
being client side, not something that is forced upon a user. The
expectation is that these trade offs won't produce any significant
variance in traffic.
> Remove postcode formatting

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Trello: https://trello.com/c/HzeMkOac/1038-return-a-temporary-cachable-redirect-for-the-postcode-checker-while-its-unavailable
GOV.UK responds with 307 for some responses to indicate a temporary
redirect. Fastly doesn't currently support them but suggested this
change.
I decided not to include the similar 303 response in here as this seemed
a bit more contentious given it is expected to originate from a POST
request: varnishcache/varnish-cache#3340 and I
don't believe we have a need.
This same change could be applied to our other VCL files but I'm not
aware of them having a need currently so it seems superfluous to
duplicate this for each.
> Recognise 307 responses as cacheable on www.gov.uk 

- lib/deploy_bouncer.rb
- spec/deploy_bouncer_spec.rb
Fastly allows backends and conditions to be set in the UI,
but subsequent VCL deploys removed these.
https://github.com/alphagov/govuk-cdn-config/blob/1c272cfc79ccb3f9fa3ff89325b70a41df0b9a00/deploy_vcl#L38
We now wish to use some Fastly features that are only
available with UI declared backends and associated conditions.
> Allow UI declared backends and conditions to persist on deploy

- lib/deploy_bouncer.rb
- lib/deploy_service.rb
- spec/deploy_bouncer_spec.rb
- spec/deploy_service_spec.rb
Fastly allows backends to be set in the UI, but subsequent VCL deploys removed these.
https://github.com/alphagov/govuk-cdn-config/blob/1c272cfc79ccb3f9fa3ff89325b70a41df0b9a00/deploy_vcl#L38
We now wish to use some Fastly features that are only available with UI declared backends and associated conditions.
This PR also re-adds these to the Bouncer deploy job which were accidentally
removed in https://github.com/alphagov/govuk-cdn-config/commit/ac468c955de96d0808c4f1ce8fa7b3bf804f0380
> Allow UI service backends to persist on deploy

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
[Fastly's best practices for cookies][1] suggest parsing cookies into
custom headers and using these headers for caching purposes, rather
than caching based on the entire Set-Cookie header (which in our case
also contains non-account-related things like A/B test bucket
assignment, Google Analytics session ID, and cookie consent
preferences).
To support accounts, we introduce two new headers:
- `GOVUK-Account-Session`: holds the session cookie value.  Set by
Fastly to pass the cookie to our apps, set by our apps to create a new
cookie.
- `GOVUK-Account-End-Session`: set by our apps to expire the cookie.
We need to make two changes to our VCL:
- `vcl_recv`: extract the cookie value and pass it in the header.
- `vcl_deliver`: if appropriate, update or expire the cookie; and, if
the response …
> Add accounts VCL (RFC 134) 

- README.md
The current links are to the old URLs
> Update Jenkins to use AWS Jenkins URLs

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We were (ab)using an A/B test to show the signed in / out header, but
now the apps have been updated to use the GOVUK-Account-Session
header, so this is no longer needed.
---
[Trello card](https://trello.com/c/uHdKokkS/643-switch-from-the-old-cookie-to-the-new-cookie)
> Remove account signed-in-state A/B header 

- README.md
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Fastly doesn't cache 406 responses by default:
https://docs.fastly.com/en/guides/http-status-codes-cached-by-default
Nor does Varnish:
https://varnish-cache.org/docs/2.1/reference/vcl.html#variables
This change is to support a change in Manuals Frontend, which will
now start returning 406 responses when requests are made with an
'Accepts' header that doesn't include `text/html`. However, in
practice we are already returning 406 responses in Government
Frontend, which are currently hitting origin.
https://github.com/alphagov/manuals-frontend/pull/1078
I've taken inspiration from https://github.com/alphagov/govuk-cdn-config/pull/316.
Trello:
https://trello.com/c/XNQhMGRt/2391-3-make-manuals-frontend-respond-to-bad-requests-with-406-status
> Recognise 406 responses as cacheable on www.gov.uk

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This caused issues where we were seeing 406's even when requesting HTML versions of the page, presumably because the endpoint was cached in Fastly after first getting a 406.
Will raise another PR tomorrow which considers request headers more.
> Revert "Recognise 406 responses as cacheable on www.gov.uk"

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Previously this was below a guard which prevented it from being set
for POST requests and the like.
> Set the GOVUK-Account-Session header for all request methods

- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
This is for the security.txt file redirect to a PaaS app which has the `vdp.cabinetoffice.gov.uk` domain:
https://github.com/alphagov/security.txt
> Add 302 redirect for security.txt in staging

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Following on from https://github.com/alphagov/govuk-cdn-config/pull/330 which is deployed in staging:
https://www.staging.publishing.service.gov.uk/.well-known/security.txt
This change enables the redirect for the security.txt file in the other environments including prod.
> Add 302 redirect for security.txt (all envs)

- vcl_templates/bouncer.vcl.erb
In 412c44946c63eaa1a922c60e86703c681dbeaacb, the /healthcheck endpoint
was removed.  It has been replaced with /healthcheck/live and
/healthcheck/ready.
> Update bouncer healthcheck

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Makes use of increased compression, reducing download size for users when browsing GOV.UK
https://trello.com/c/u9qiWQr1/2476-3-enable-brotli-compression-in-fastly-for-production
> Add brotli vcl config

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Feedback from Fastly support:
> It looks like `www.gov.uk` doesn't have the normalization vcl in vcl_recv for Brotli support. Once you add that in this should work correctly.
```
if (req.http.Fastly-Orig-Accept-Encoding) {
if (req.http.Fastly-Orig-Accept-Encoding ~ "\bbr\b") {
set req.http.Accept-Encoding = "br";
}
}
```
> Add normalization vcl for Brotli support

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
As recommended in Fastly's documentation: https://developer.fastly.com/reference/http-headers/Fastly-Client-IP
If a client sets this header themselves, Fastly will use it. This has implications for us as we set the value of this header as the value of another header 'True-Client-IP', which is later set as the `real_ip_header` in [Nginx config at origin](https://github.com/alphagov/govuk-puppet/blob/32c1bbbb10067078c1406170666a135b4a10aaea/modules/router/templates/router_include.conf.erb#L12).
> Prevent modification of Fastly-Client-IP by client

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Currently we're setting this header on every request, which means it's
usually getting set to the empty string.  This has resulted in
finder-frontend making a request to account-api every time the brexit
checker results page gets loaded, because it just checks if the header
is set at all, not if it's set with a nonempty value.
> Only set GOVUK-Account-Session if cookie is present

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Follows suggestion here: https://developer.fastly.com/solutions/examples/manipulate-query-string
> Improve cache hit rate by manipulating query params

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This will strip query strings from the homepage using a Fastly function [querystring-remove](https://developer.fastly.com/reference/vcl/functions/query-string/querystring-remove)
The homepage's behaviour doesn't change based on query strings so we don't need to include the query params in the cache key.
> Remove query strings from homepage

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We have an issue where if a user logs in or logs out, and returns to a
page they have cached, the account navigation in the header doesn't
update until the cache period expires.
Such pages return `Vary: GOVUK-Account-Session` (which makes Fastly
cache them correctly), and we prevent shared caches from holding
them (with `Cache-Control: private`), but the user's browser still
caches them.  This causes the problem described above: something has
changed, but the user's browser doesn't know what, and so it serves
the old version.
The fix is to make caching depend on cookies, so that if the user's
cookies change, the browser knows not to use the cached entry.  The
downside is that we can't tell the browser to be any more granular:
if *any* cookie changes, the browser will make a request to …
> Set `Vary: Cookie` for account pages

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We will use this to show the appropriate navigation (signed in vs
signed out), and `Vary` based on it so we only cache one copy for all
signed in users and one copy for all signed out users, rather than one
copy each for all signed in users.
I don't think we need to add a case for:
if (resp.http.Vary ~ "GOVUK-Account-Session-Exists")
because `~` is a regex match, so the `~ "GOVUK-Account-Session"` check
should be sufficient.
See also the progressive enhancement ADR for account-api[1].
[1] https://github.com/alphagov/account-api/blob/main/docs/adr/002-progressive-enhancement.md
---
[Trello card](https://trello.com/c/4wd8du6X/987-implement-navigation-caching-behaviour)
> Add custom GOVUK-Account-Session-Exists request header

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We specify in the govuk_personalisation docs that, if you use it, you *must*
set appropriate caching headers (like `Vary: GOVUK-Account-Session` or
`Cache-Control: no-store`) otherwise we risk showing user B a response
generated based on user A's session:
> Set the `Vary: GOVUK-Account-Session` response header.
>
> This is called as a `before_action`, to ensure that pages
> rendered using one user's session are not served to another by
> our CDN.  You should only skip this action if you are certain
> that the response does not include any personalisation, or if
> you prevent caching in some other way (for example, with
> `Cache-Control: no-store`).
https://github.com/alphagov/govuk_personalisation/blob/a5413087190099a6d74a1912f97acef75ec5de42/lib/govuk_personalisation/controller_concern.rb …
> Never cache pages which manipulate the user's session 

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
The account session cookie is set by govuk_personalisation, and is in
one of two formats:
- "#{base64(encrypt(session))}"
- "#{base64(encrypt(session))$$#{flash}"
We want to bypass the cache if there is a flash message, so that the
app can render it.  We considered doing flash messages as a form of
progressive enhancement, but decided that doing them server-side made
more sense and was simpler.
---
[Trello card](https://trello.com/c/V8IhzaMH/983-success-banner-on-content-pages-progressive-enchantment)
> Bypass cache if there is a flash message to show

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Previously, we bypassed Fastly when there is a flash message in the
session.  But this isn't enough: there's also our Varnish.
A request header with a corresponding `Vary` response header is the
standard way to handle a request that is conditionally cacheable so,
rather than implementing a further special case for our Varnish, just
go for the standard.
Then, the way a page which shows a flash and account navigation but
doesn't use a user's attributes will work is:
1. It reads and decodes the account session header
2. It sets `Vary: GOVUK-Account-Session-Exists`
3. It sets `Vary: GOVUK-Account-Session-Flash`
4. It fetches the appropriate template from static
5. It reads the flash to determine what will be shown
This is better than just setting `Vary: GOVUK-Account-Session` (which
would …
> Use a custom request header for account flash caching purposes

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
These IP addresses were [added in 2016](https://github.com/alphagov/govuk-cdn-config/commit/570d4e941f6c542b2dfcd96255b5c7b7916dee45) so that Fastly staff could purge our content if required, but only if they made the request from a Fastly cache node.
I'm not aware of this ever having been necessary since, and should it be so, we would be able to add the required IPs back again either here, or in the Fastly management console.
In addition, Fastly now advise [using API tokens to authenticate purge requests](https://docs.fastly.com/en/guides/authenticating-api-purge-requests).
I've added a [Trello card to the Platform Reliability team backlog][1] to switch this to using API tokens.
[1]: https://trello.com/c/O5Wy2X9w/2613-authenticate-fastly-purge-requests-with-an-api-token
We no longer have …
> Update Fastly purge request IP allow list

- vcl_templates/www.vcl.erb
A couple of minor changes to support adding an `integration-eks` service in front of the EKS cluster. See individual commit messages for details.
* [Define the allowed_ip_addresses ACL in all non-prod environments.](https://github.com/alphagov/govuk-cdn-config/commit/b57bcc04a3f5ffe412b3356883abced7058e6d30)
* [Allow setting the Host header for requests to the EKS backend.](https://github.com/alphagov/govuk-cdn-config/commit/c9a5e96ec5655a717baee2293bc6785514abb17f)
Prerequisite for alphagov/govuk-cdn-config-secrets#147.
[Trello](https://trello.com/c/9BPpFRBe/851)
> Template support for forwarding traffic to EKS.

- lib/deploy_service.rb
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/mirror-test.out.vcl
- spec/test-outputs/performanceplatform-integration.out.vcl
- spec/test-outputs/performanceplatform-production.out.vcl
- spec/test-outputs/performanceplatform-staging.out.vcl
- spec/test-outputs/performanceplatform-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/bouncer.vcl.erb
- vcl_templates/mirror.vcl.erb
- vcl_templates/performanceplatform.vcl.erb
- vcl_templates/www.vcl.erb
Update Fastly ACLs and ensure that ACLs apply to the upcoming `*-eks` configurations. Getting this existing configuration into a good state will simplify adding the other EKS configs (staging, production x www, assets) whether we continue to use this codebase or port to Terraform.
- [Allow specifying CIDRs in the allowed_ip_addresses ACL.](https://github.com/alphagov/govuk-cdn-config/commit/9dca81ae7f9adbb7b597b75fb59b31bad68b24f0) Needed for alphagov/govuk-cdn-config-secrets#148.
- [Add a dry-run mode to deploy_service.rb.](https://github.com/alphagov/govuk-cdn-config/commit/716dd3cc0c7f268be20e8a9b584cab090fa39fa9)
- [Clean up the purge ACLs and include them in EKS configs.](https://github.com/alphagov/govuk-cdn-config/commit/1bfdf8c774198b41abf350090414d325b1ae54b6)
- Include the purge …
> Update Fastly ACLs

- lib/deploy_dictionaries.rb
- lib/deploy_service.rb
- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- vcl_templates/assets-eks.vcl.erb
- vcl_templates/www-eks.vcl.erb
This is probably the simplest way to allow rolling out the `*-eks` configs from the `CDN: deploy service` Jenkins job. We need to use unique service names (rather than additional environments within the existing services) for the EKS configs so that they can be chosen in the "Build with parameters" page on Jenkins.
Alternatively we could modify the script to special-case the `*-eks` configs, but that seems even bodgier than just adding these symlinks. Once GOV.UK traffic is permanently being served from Kubernetes, we'll delete these extra configs anyway.
See alphagov/govuk-cdn-config-secrets#149.
Deployed locally with `bundle exec deploy_service www-eks integration`.
Best reviewed commit-by-commit, since a lot of the change is just auto-generated golden test outputs in commit deb712e. …
> Add symlinks for www-eks and assets-eks services.

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This functionality is currently handled by varnish in EC2, but as part of the move to EKS we need to move this to fastly.
Trello: https://trello.com/c/HXtsiNCO/855-strip-cookies-at-fastly
> Strip cookies for applications that don't them at fastly

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This needs porting from varnish to fastly configuration.
https://github.com/alphagov/govuk-puppet/commit/d8678975bf75cba14de867cb9718c42a3696b794
> Add: fastly signon callback cookie setting

- vcl_templates/www.vcl.erb
This feature was added because the ingress in EKS was not configured
properly to accept the original host header of fastly.
This had now been fixed in [here](https://github.com/alphagov/govuk-helm-charts/pull/270)
> Remove the feature to set header in the backend

- configs/dictionaries/active_ab_tests.yaml
Assigning users to Z is unexpected behaviour for smokey. See
https://github.com/alphagov/smokey/blob/2ba441d489c1cfb4a96401b46c8f07a5c279cd99/features/step_definitions/ab_testing_steps.rb#L43
Turning test off whilst we update smokey
> Turn NewBrowse test off

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We haven't displayed the link to the coronavirus landing page in months, and should remove it from here too for consistency.
> Remove link to coronavirus landing page

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Roll back https://github.com/alphagov/govuk-cdn-config/pull/374
This PR was causing AB test cookies to be stripped.
> Revert Cookie stripping

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-integration.out.vcl
- vcl_templates/www.vcl.erb
This was breaking the A/B test smoke tests in EC2 integration, which causes confusion. I'm not sure we even need to do cookie stripping in the EC2-backed services.
Partially reverts #373.
https://trello.com/c/HXtsiNCO
> Don't strip cookies in EC2-backed services, only EKS ones.

- spec/vcl_generation_spec.rb
- spec/www_vcl_erb_spec.rb
- vcl_templates/www.vcl.erb
In the new EKS rig, an origin request for `/` is relatively expensive so we need to be able to set this to a dedicated path that we can serve more cheaply. Fastly sends a *lot* of healthchecks.
Tested: successfully deployed the new staging-eks www service. No diffs for existing services.
https://trello.com/c/gipscM7t
> Allow specifying the path for the www backend healthcheck.

- deploy-dictionaries.sh
- deploy-service.sh
We only need to fetch the head of the main branch of `govuk-cdn-config-secrets`. This speeds up deployment and saves a little bit on resource usage.
Tested: scripts still work locally.
> Have the deploy scripts run a shallow git clone.

- vcl_templates/www.vcl.erb
Whilst we are testing deploying the production environment we'd like restrict access from the general public.
> Enable IP allowlist for the EKS production environment

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This is copied from the EC2-based Varnish config. This is required for replatforming work, since we will be retiring the EC2-based Varnish services.
I have tested it using Fastly Fiddle.
This is integration-only at this point to test before deploying everywhere.
Trello: https://trello.com/c/88bU7Qmm/854-normalise-accept-encoding-header-at-fastly
> Copy Accept-Encoding normalisation from EC2 Varnish

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
Tests in integration look good, should be safe to roll out everywhere.
See also: https://github.com/alphagov/govuk-cdn-config/pull/379
https://trello.com/c/HXtsiNCO/855-strip-cookies-at-fastly
> Strip Accept-Encoding header in all environments

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
[Trello card](https://trello.com/c/O5Wy2X9w/2946-authenticate-fastly-purge-requests-with-an-api-token-3)
Now that the "Clear CDN Cache" Jenkins job has been updated to authenticate its PURGE requests to Fastly with an API token[^1], and the developer docs have been updated to make it clear that manual PURGE requests must similarly be authenticated[^2], it should now be safe to require authentication for every PURGE request, and remove the IP allowlist.
[^1]: https://github.com/alphagov/govuk-puppet/pull/11775
[^2]: https://github.com/alphagov/govuk-developer-docs/pull/3635
> Remove purge allowlist

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This is a temporary change to enable sending a proportion of traffic to the new k8s GOV.UK stack. It is enabled with a config variable, and has been set up for use in staging before the production test next week.
https://trello.com/c/a6qhzsAy/987-create-fastly-config-for-production-traffic-split-experiment
> Add config for replatforming traffic split experiment

- vcl_templates/www.vcl.erb
Test in staging was successful; this sets the backend URLs to the production ones, and sets the ratio to 1:20 (5%) going to the EKS platform.
https://trello.com/c/a6qhzsAy/987-create-fastly-config-for-production-traffic-split-experiment
> Update replatforming traffic split URLs to production; set traffic split ratio to 5%

- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
This fixes an issue where the X-Forwarded-Host header was incorrect, as it was being set from the request Host header which was being re-written previously. This moves the logic to set the proxy headers earlier in the vcl_recv subroutine as to ensure they are using the original header information.
Been tested in integration - fixed the X-Forwarded-Host header to actually be set as the request Host.
> Set proxy headers with original request headers

- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We previously renamed the Production EKS service/environment from production-eks to production. However forgot to update conditional to apply IP allow lists only to production-eks.
> Fix IP allow lists for Production EKS

- lib/deploy_bouncer.rb
- lib/deploy_service.rb
- lib/render_template.rb
- spec/render_template_spec.rb
- spec/test-outputs/bouncer-integration.out.vcl
- spec/test-outputs/bouncer-production.out.vcl
- spec/test-outputs/bouncer-staging.out.vcl
- spec/test-outputs/bouncer-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- spec/vcl_generation_spec.rb
- spec/www_vcl_erb_spec.rb
- vcl_templates/www.vcl.erb
This makes a couple of changes to the RenderTemplate class:
- It now accepts an argument of locals which sets local variables, this allows the RenderTemplate class to be used for bouncer VCL templates
- It adds a `#render_partial` to allow the embedding of partial files inside a VCL template
My motivation for adding this in is that I want to add the same partial to a number of VCL templates and was finding myself bogged down with repetitive code and implementation inconsistencies. This work is applied in: https://github.com/alphagov/govuk-cdn-config/pull/416 which is currently open as a draft.
This …
> More flexible template rendering with partials

- lib/deploy_bouncer.rb
- lib/deploy_service.rb
- lib/render_template.rb
- spec/render_template_spec.rb
- spec/test-outputs/bouncer-integration.out.vcl
- spec/test-outputs/bouncer-production.out.vcl
- spec/test-outputs/bouncer-staging.out.vcl
- spec/test-outputs/bouncer-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- spec/vcl_generation_spec.rb
- spec/www_vcl_erb_spec.rb
- vcl_templates/www.vcl.erb
This reintroduces the reverted code from https://github.com/alphagov/govuk-cdn-config/pull/420 and fixes the issue that blocked it - which was the introduction of a new variable configuration into the template from https://github.com/alphagov/govuk-cdn-config/pull/419
As https://github.com/alphagov/govuk-cdn-config/pull/420 was already reviewed it's easiest to review this PR by looking at just the 2nd commit.
> Reinstate #420

- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- vcl_templates/assets.vcl.erb
This change depends on a corresponding Puppet PR [1]
This removes the setting of a HTTP Host header for when Fastly is
proxying to origin. This was previously needed because there wasn't
vhosts configured for the integration and staging asset hosts, so
proxying to them would fail.
It's not necessarily bad that we change the host here, my motivation is
more based on consistency as this is behaviour we don't follow in our
other CDN configs (www and bouncer). I believe this inconsistency
contributed to a recent incident [2] and thus believe that resolving it
we reduce the risk of further surprises caused by quirky configuration.
[1]: https://github.com/alphagov/govuk-puppet/pull/11871
[2]: https://docs.google.com/document/d/18kIgL2F0PPCZSjSCLH5z0hOq3Gn8wmCwxrlR1bOPric/edit#heading=h.e85n7w4jf …
> Stop setting http_host for requests to assets-origin

- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- vcl_templates/assets.vcl.erb
This adds config to enable split traffic for the asset services to send traffic to the EKS cluster. This is to be used for our live traffic experiments.
> Enable traffic split for asset services

- vcl_templates/www.vcl.erb
To test the fastly config change whether it causes initial set of errors.
> Use max weight to start traffic split

- vcl_templates/www.vcl.erb
> Set traffic split for www to 5%

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Set traffic split for www and assets to 10%

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Set traffic split for www and assets to 20%

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Set traffic split for www and assets to 50%

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Set traffic split ratio to 1:999

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Set traffic split ratio to 1:1

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Set traffic split ratio to 19:1

- vcl_templates/www.vcl.erb
> Use healthcheck hostname for probes instead of origin hostname for EKS backend

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This moves the logic to strip cookie after the logic for setting up the A/B test in the recv vcl routine. This is because the A/B tests need access to the cookie to understand whether a user has already been assigned a variant.
> Strip cookies after using setting up A/B test

- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/mirror.vcl.erb
Deployment: needs manual rollout; see [playbook](https://docs.publishing.service.gov.uk/manual/cdn.html#deploying-fastly).
> Add EKS egress addresses to cache purge ACLs.

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We're not seeing a cookie being set in various environments and just want to check that the logic snippet isn't the issue as the AB-EXample works.
> Add hard coded setting of BankHolidaysTest cookie

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/_multivariate_tests.vcl.erb
- vcl_templates/www.vcl.erb
The dynamic code used to generate cookies for AB tests first checks
that the user has consented to cookies. This value is stored in a
cookie called `cookie_policy`. If the `cookie_policy` cookie doesn't
contain a value, the code won't execute. That's what was happening
here, and had the effect of the AB test cookies not being created.
The Example AB test doesn't check the value of the `cookie_policy`
cookie, so that cookie was being set as expected.
When a request is made to Fastly for a page, the header contains the
cookie information. However, if there's a cache-miss and we need to
call the …
> Fix setting cookies for AB tests

- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- spec/test-outputs/bouncer-integration.out.vcl
- spec/test-outputs/bouncer-production.out.vcl
- spec/test-outputs/bouncer-staging.out.vcl
- spec/test-outputs/bouncer-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/_security_txt_request.vcl.erb
- vcl_templates/_security_txt_response.vcl.erb
- vcl_templates/assets.vcl.erb
- vcl_templates/bouncer.vcl.erb
- vcl_templates/www.vcl.erb
This configuration redirects requests for the security.txt file to Cabinet Office's vulnerability disclosure program.
We want to add this feature to assets.publishing.service.gov.uk and all of the sites that bouncer caters for.
The configuration is identical to that for www.gov.uk, so I've extracted that as a partial and reused it across the services.
Bouncer had its stale cache grace time of 1 day specified in seconds, so I've tweaked that to `24h` so that it's the same as the other two.
I regenerated the specs with each commit to keep the config changes connected.
DGU's config is held in the govuk-aws repo, but that will be included in this work. 
https://trello.com/c/VLBjBTMe/313-put-securitytxt-on-bouncer-and-dgu
⚠️ The changes need to be deployed manually to all relevant …
> Add security.txt to the assets and bouncer services

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/mirror-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/mirror.vcl.erb
- vcl_templates/www.vcl.erb
In March 2018, in 26a0edb0c1138b5cbedd741e396d942cf117cd8c, code was added to intercept requests for URLs beginning with "/apply-for-a-licence/", which:
> Added a request header containing the TLS version number for requests to the Licensify app
> (This is so we can block requests with TLS versions below 1.2 from submitting, for payment security reasons)
However, in December 2022, in
https://github.com/alphagov/govuk-puppet/pull/11931/commits/46d98aaec4eaf664f8a078ea12d2ec03ada4b18c, we dropped TLS 1 and 1.1 support at the nginx level. So the special case added just for Licensify is no longer necessary.
This was uncovered as part of the following Trello card: https://trello.com/c/TbvosEgo/3101-staging-test-define-list-of-features-that-wont-currently-work-on-cloudfront
⚠️ The changes need …
> Remove Licensify TLS hack

- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
This allows you to override the default backend and have the request served by a mirror. Helpful to check if the mirrors are working. This header only works in Staging.
Might be easier to review using the Split View.
> Add 'Backend-Override' header to select backend
