alphagov/govuk-cdn-config

- README.md
Update README to give a hint as to how the configs can be deployed.
> How the cdn configs can be deployed

- vcl_templates/assets.vcl.erb
This has changed in production
> Update assets domain in staging

- vcl_templates/performanceplatform_admin.vcl.erb
- vcl_templates/performanceplatform_stagecraft.vcl.erb
- vcl_templates/www.vcl.erb
This has never had a content designer look at it before now. Tom Hughes has suggested a couple of tweaks to make this fit better with GOV.UK style.
> Update error page synthetic text

- vcl_templates/www.vcl.erb
> Add in missing bracket

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
Switch Mirror provider to use Carrenza instead of Skyscape
> Use Carrenza as mirror provider

- vcl_templates/www.vcl.erb
The cookie is not being set properly, therefore we need to roll this back.
trello: https://trello.com/c/S5jp2jih/179-setup-technical-implementation-for-a-b-testing-the-blue-box
> Revert blue box ab test

- vcl_templates/bouncer.vcl.erb
[Trello card](https://trello.com/c/G8tsen8Y/296-add-whitechapel-ip-address-ranges-to-our-config)
> Add White Chapel Building IP Addresses

- vcl_templates/www.vcl.erb
Reverts #69 and #70 now the test has completed.
> Remove CloudPiercer verification

- vcl_templates/www.vcl.erb
This reflects the mixture of IPs that are now listed.
> Rename office_ip_addresses to allowed_ip_addresses

- vcl_templates/www.vcl.erb
We really should have automated tests for this repo (documented in https://trello.com/c/y6MIgxjp).
https://trello.com/c/ml5fQQxS
> Add missing semicolon to fix CSP experiment

- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- vcl_templates/assets.vcl.erb
Context
We have issues with purging assets.
Decision
After discussion with Fastly the recommendation is to make this change to the
VCL. Further details are in the trello card
(https://trello.com/c/RASJllyU/517-hmrc-paye-tools).
> Update VCL config per recommendation

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Reverts alphagov/govuk-cdn-config#153
> Revert "Cache non-GET/HEAD requests with 404/405 responses"

- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- vcl_templates/mirror.vcl.erb
Fix a missing opening brace in mirror vcl template
> fix missing opening brace in mirror template

- spec/test-outputs/www-integration.out.vcl
- vcl_templates/www.vcl.erb
So that the Cache Clearing Service can submit PURGE requests in
Integration.
> Add Integration NAT gateways to purge_ip_whitelist

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
This is intended to be a quick rollback mechanism (a fast feature toggle).
https://trello.com/c/p0lAUSLg/1276
> Add search reranker header to www vcl

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
Serve a 503 error page when /search is unavailable
> Return a 503 error page for /search

- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We want these pages to not be affected by query strings as well.
> Add more coronavirus pages

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- vcl_templates/www.vcl.erb
We don't want to deploy this yet and it's blocking deploying other things.
> Revert disabling /search

- ab_tests/ab_tests.yaml
- configs/dictionaries/ab_test_expiries.yaml
- configs/dictionaries/active_ab_tests.yaml
- configs/dictionaries/showpartsinresultsabtest_percentages.yaml
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
Reverts alphagov/govuk-cdn-config#263
> Revert "Add parts-in-results A/B test"

- spec/test-outputs/www-staging.out.vcl
- spec/vcl_generation_spec.rb
- vcl_templates/www.vcl.erb
See alphagov/govuk-cdn-config-secrets#131.
This only affects Staging for now.
Co-authored-by: @OllieJC
> Include private VCL from govuk-cdn-secrets for mitigations (in staging).

- spec/test-outputs/apt-test.out.vcl
- spec/test-outputs/assets-test.out.vcl
- spec/test-outputs/mirror-test.out.vcl
- spec/test-outputs/performanceplatform-test.out.vcl
- spec/test-outputs/servicegovuk-test.out.vcl
- spec/test-outputs/tldredirect-test.out.vcl
- spec/test-outputs/www-test.out.vcl
- spec/vcl_generation_spec.rb
- vcl_templates/www.vcl.erb
We are creating a new ECS-based platform for GOV.UK.
This PR adds the test spec for the new fastly service for this new platform.
Ref:
[1] [trello card](https://trello.com/c/TjJOKSKp/404-basic-auth-for-integration-environment)
> Add test spec for Test environment

- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/www.vcl.erb
We're checking if SameSite=strict is causing our Safari issue.
> Set account cookie as SameSite=lax

- configs/dictionaries/active_ab_tests.yaml
Just switching it on at zero, and slowly ramping it up in subsequent updates.
https://trello.com/c/Z0MXay8A/445-get-prs-ready-for-switching-on-the-ab-test
> Update ExploreMenuAbTestable to be active at 100-0

- configs/dictionaries/active_ab_tests.yaml
Going to try checking on Staging instead of Integration.
> Re-activate NewBrowse test at 0%

- vcl_templates/www.vcl.erb
For replatforming traffic split experiment
https://docs.google.com/spreadsheets/d/1cw-W3iPcLlThKCUfQzTY-LWIRam0h4lw3qkpN0gwNNg/edit#gid=104889717
> Update traffic split ratio to 1:19

- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
> Health check probe updates for traffic split

- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- spec/test-outputs/mirror-integration.out.vcl
- spec/test-outputs/mirror-production.out.vcl
- spec/test-outputs/mirror-staging.out.vcl
- spec/test-outputs/mirror-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- vcl_templates/assets.vcl.erb
- vcl_templates/mirror.vcl.erb
- vcl_templates/www.vcl.erb
> Block known bad signatures

- fastly.yaml
- spec/test-outputs/assets-eks-integration.out.vcl
- spec/test-outputs/assets-eks-production.out.vcl
- spec/test-outputs/assets-eks-staging.out.vcl
- spec/test-outputs/assets-eks-test.out.vcl
- spec/test-outputs/assets-integration.out.vcl
- spec/test-outputs/assets-production.out.vcl
- spec/test-outputs/assets-staging.out.vcl
- spec/test-outputs/assets-test.out.vcl
- spec/test-outputs/www-eks-integration.out.vcl
- spec/test-outputs/www-eks-production.out.vcl
- spec/test-outputs/www-eks-staging.out.vcl
- spec/test-outputs/www-eks-test.out.vcl
- spec/test-outputs/www-integration.out.vcl
- spec/test-outputs/www-production.out.vcl
- spec/test-outputs/www-staging.out.vcl
- spec/test-outputs/www-test.out.vcl
- spec/vcl_generation_spec.rb
- spec/www_vcl_erb_spec.rb
- vcl_templates/assets.vcl.erb
- vcl_templates/www.vcl.erb
See alphagov/govuk-cdn-config-secrets#184 for the config change which goes alongside this.
While we're there, delete some disused config.
Easiest to review commit-by-commit.
https://trello.com/c/RkVL0rMF
Tested: already deployed (in integration and staging).
> Make healthcheck probes more configurable.

- README.md
This commit:
- Clarifies what Fastly API token is needed
- Not to bother attempting to deploy to `*-eks`
- Links the 'service name' to the ones used in Fastly
- Frontloads the Fastly information to the top of the doc
> Quick README refresh
